CREATE TABLE IF NOT EXISTS clients
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(40) NOT NULL CHECK(first_name <> ''),
    last_name VARCHAR(40) NOT NULL CHECK(last_name <> ''),
    cpf VARCHAR(15) NOT NULL UNIQUE,
    sex VARCHAR(15) NOT NULL,
    genre VARCHAR(15) NOT NULL,
    birth_date DATE NOT NULL,
    marital_status VARCHAR(15) NOT NULL,
    education VARCHAR(30) NOT NULL
);

