CREATE TYPE SEX_ENUM AS ENUM('MASCULINO', 'FEMININO');

CREATE TYPE GENRE_ENUM AS ENUM
(
    'LESBICAS', 'GAYS', 'BISSEXUAIS', 'TRANSGENERO', 'QUEER', 'INTERSEXO', 'ASSEXUAL', 'PANSEXUAIS', 'OUTRO', 'NENHUM'
);

CREATE TYPE MARITAL_STATUS_ENUM AS ENUM('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'VIUVO');

CREATE TYPE EDUCATION_ENUM AS ENUM
(
    'FUNDAMENTAL_INCOMPLETO',
    'FUNDAMENTAL_COMPLETO',
    'MEDIO_COMPLETO',
    'TECNICO_COMPLETO',
    'SUPERIOR_COMPLETO',
    'ESPECIALIZACAO_COMPLETA',
    'MESTRADO_COMPLETO',
    'DOUTORADO_COMPLETO'
);
