package io.portfolio.micro_cliente.client.domain.enums;

public enum EducationEnum {
    INCOMPLETE,
    COMPLETE_PRIMARY_EDUCATION,
    COMPLETE_HIGH_SCHOOL,
    COMPLETE_TECHNICAL_EDUCATION,
    COMPLETE_HIGHER_EDUCATION,
    COMPLETE_SPECIALIZATION,
    COMPLETE_MASTERS_DEGREE,
    FULL_DOCTORATE;
}
